sudo: required
language: node_js
node_js:
  - "6.9.5"

branches:
  only:
    - master

#addons:
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable
#      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli
  - npm install
  - npm install angular-cli

script:
  - ng build --prod
  - ng lint
  - ng test

notifications:
  email:
    on_failure: change
    on_success: change


## sudo: required
# dist: trusty
#language: node_js
#node_js:
#  - '6.9'

#branches:
#  only:
#    - master

#addons:
#apt:
#  sources:
#    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

#before_script:
#  - npm install -g angular-cli
#  - npm install -g karma
#  - npm install

#script:
#  - ng build --prod

#script: karma start config/karma.conf.js --single-run

